### ISSUE TITLE
Sync utility is not creating Sales Order in Quickbooks and displays these errors:

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#1]
humberto.ramirez@usa.net

![image](https://cloud.githubusercontent.com/assets/25314838/22233968/72673ef6-e1c2-11e6-9044-2973132a7bba.png)

**Comment by Xi23000** [comment]
I have tested several times and only on a few tries it created the Sales order in Quickbooks.
Sometimes I had to logoff from the website and log back in for this to work, it is NOT working reliably.

**Comment by consuspk** [comment]
fixed
