### ISSUE TITLE
Urgent !!! Sync utility has stopped working.

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#10]
It now displays a screen asking for database credentials:

![image](https://cloud.githubusercontent.com/assets/25314838/22343715/1c09994e-e3c7-11e6-8bf3-bfd3ded2eee9.png)

**Comment by consuspk** [comment]
There is an invalid reference to QuickBooks Sales Rep "LR" in the SalesOrder.  QuickBooks error message: Invalid argument.  The specified record does not exist in the list.


Please add all Sales Rep

**Comment by Xi23000** [comment]
Got it

**Comment by Xi23000** [comment]
I had to create a test user in SQL to be able to login, It wouldn't accept the consus1 user name, why??

**Comment by Xi23000** [comment]
I had to create a test user in SQL to be able to login, It wouldn't accept the consus1 user name, why??

**Comment by consuspk** [comment]
might be SQL user don't have permission to login

**Comment by Xi23000** [comment]
OK, I'm going to close issue, but this had never happened before.
