### ISSUE TITLE
Customer List on Website does not match list in Quickbooks

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#11]
It appears as if the website is missing some customers, the customer list should be in sync

![image](https://cloud.githubusercontent.com/assets/25314838/22344903/ee260936-e3cb-11e6-844b-0eb27abd4b30.png)

![image](https://cloud.githubusercontent.com/assets/25314838/22344955/2ca8adda-e3cc-11e6-9f64-267ce1bc9c72.png)

**Comment by consuspk** [comment]
because we put condition on customer import, only customer will import have email address and no repetitions

**Comment by Xi23000** [comment]
No Repetitions makes sense, but please sync also the ones without emails (I understand they wont's be able to login)

**Comment by consuspk** [comment]
updated

**Comment by Xi23000** [comment]
Some of this accounts I don't want to show/display, what can be done?  The ones that say "miscellaneous"

![image](https://cloud.githubusercontent.com/assets/25314838/22376948/13851660-e47e-11e6-9c82-2957336b50c5.png)

**Comment by Xi23000** [comment]
What you think regarding this?

**Comment by consuspk** [comment]
Hold for next Phase

**Comment by consuspk** [comment]
This list by default shows the Active QB Customer in QB,
further we can add another option on website to mark them Archive so you will see only customer which are not Archive let me know if it works

**Comment by Xi23000** [comment]
What is the sync logic? Every time the sync runs it transfers the customer that are not currently in SQL?

**Comment by consuspk** [comment]
Import new customers and update existing.

**Comment by Xi23000** [comment]
Just so we can finish with this let's change the logic a bit, you told me this:
_"we put condition on customer import, only customer will import have email address and no repetitions"_

Lets do the following:

Import the Customer even if it has no email address
If the email address of the customer is already in the website database then clear/leave blank email address for that customer being imported

And in the Admin web site a list of "Excluded Customers" any customer on that list won't show on the web site list of customers, This is done because certain customer must be excluded.

**Comment by consuspk** [comment]
Following part is done, second in next phase

Import the Customer even if it has no email address
If the email address of the customer is already in the website database then clear/leave blank email address for that customer being imported
