### ISSUE TITLE
Error while adding sales person

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#14]
The following error was displayed while adding a sales person:

![image](https://cloud.githubusercontent.com/assets/25314838/22375520/5b6983b8-e478-11e6-9ffd-824329ba0450.png)

**Comment by consuspk** [comment]
how you produce this, unable to debug

**Comment by Xi23000** [comment]
I started adding several "Sales Person" when I was going by the 3rd or 4th it started happening.

**Comment by consuspk** [comment]
Fixed
