### ISSUE TITLE
Critical, Customer Job on Sales Order, doesn't match with Website selection

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#15]
When you select a customer on the web site and create an order, in the created sales order in QB the customer Job doesn't match the customer selected in the Website, it appears to be using the name instead.
Even more critical, in one of the test the first and last on the web site were empty and I typed "First Name" and "Last Name" the system replaced the company name with those values.

I prefer that for existing customers that came from Quickbooks this information is not updated in Quickbooks when an order is placed.

![image](https://cloud.githubusercontent.com/assets/25314838/22377939/b5e750d2-e481-11e6-97b5-877243c26170.png)

![image](https://cloud.githubusercontent.com/assets/25314838/22377998/e8826c84-e481-11e6-9a0f-9187a79c5065.png)

![image](https://cloud.githubusercontent.com/assets/25314838/22377841/518b3388-e481-11e6-9174-266ed4b55fd2.png)

![image](https://cloud.githubusercontent.com/assets/25314838/22378050/1d77dc58-e482-11e6-82e9-b059475b3148.png)

**Comment by consuspk** [comment]
Updated
