### ISSUE TITLE
QB Database in production

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#17]
So far we have used/tested the website and the sync with a copy of QB, the production database is on a network share, what steps are necessary to prepare the SQL databases for initial sync when I start working on a different QB FIle?

**Comment by consuspk** [comment]
in the database there is a procedure called "usp_empty_database"  you can execute it when you want to sync your Live QB
You can open the QB company and start syncing after making SQL Server database empty and checking the settings

**Comment by Xi23000** [comment]
Can you please review this steps is this correct?

1.- Open QB w/admin for current company
2.- Open Sync
3.- Click on gear and change QB company
4.- Save Settings
5.- Open new company in QB w/admin
6.- Switch to Sync and click on gear
7.- QB Certificate authorization will show
8.- Authorize Sync

**Comment by consuspk** [comment]
Yes. it seems to be fine
