### ISSUE TITLE
Ship via / Backorder type options

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#2]
**Ship via Options:**   
Pick up Complete
Pick up Partial 
Delivery Complete
Delivery Partial

**Backorder Type Options**
Cancel
Air
Truck
Same day

![image](https://cloud.githubusercontent.com/assets/25314838/22234067/20cb8d62-e1c3-11e6-8eb4-e9a9a0a450fb.png)

**Comment by Xi23000** [comment]
The change is now reflected on the web site, however the information doesn't reflect on Quickbooks
Possibly because the length of the field is limited to 15 characters (Ship Via on the Sales Order also referred to as Shipping method).
Please replace the options with this shorter names:
Pick up Comp
Pick up Part
Delivery Comp
Delivery Part

**Comment by consuspk** [comment]
define these ship method with same name in QuickBooks

**Comment by Xi23000** [comment]
This is working well for "Ship via" how ever the info from "Back Order Type" is not transferred to QB, In the sales order in QB is located next to Ship Via, and called B/O Type

![image](https://cloud.githubusercontent.com/assets/25314838/22345361/d5111dc6-e3cd-11e6-8e02-6ad9d1c16230.png)

**Comment by consuspk** [comment]
Done

**Comment by Xi23000** [comment]
This was fixed, but somehow the issue reappeared

Ship Via:
Pick up Complete  ---> Pick up Comp
Pick up Partial   ---> Pick up Part
Delivery Complete ---> Delivery Comp
Delivery Partial  ---> Delivery Part

Back Order Type:
Cancel
Air
Truck

Payment type:

Add:
Open Account

Just so I can test I edited checkout.aspx manually.

**Comment by consuspk** [comment]
its fixed, please don't edit any page manually

**Comment by Xi23000** [comment]
I will not edit the page manually, what is the proper way to edit?

**Comment by consuspk** [comment]
we will provide you code after completion, then you can edit

**Comment by Xi23000** [comment]
This happened again, the values were reversed
I'm sorry I edit the file manually just so we can continue testing.
