### ISSUE TITLE
Error while doing check-out

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#21]
Error Occured: **Cannot set column 'Description'. The value violates the MaxLength limit of this column.**

Aparently this part number has something that triggers the error: 08185

This is the description for the item: PERMATEX® Black Nitrile Disposable Gloves (Large, 100 ct box)

![image](https://cloud.githubusercontent.com/assets/25314838/22488497/59c20038-e7e0-11e6-80f8-8573fa2d8bbe.png)

![image](https://cloud.githubusercontent.com/assets/25314838/22489337/f16fd852-e7e4-11e6-944b-7a8b2f00cbbe.png)

**Comment by consuspk** [comment]
fixed and length extended

**Comment by Xi23000** [comment]
Need to review
