### ISSUE TITLE
Control on the email delivery

### ISSUE THREAD

**Issue by Xi23000** [Xi23000/qb1#8]
I would like to know where to change to content of the text sent with the email confirmation, also the recipients.

**Comment by consuspk** [comment]
will discuss in next phase

**Comment by Xi23000** [comment]
That's reasonable but for now I can I manually edit the text file containing this settings QBSync.exe.config or something similar?

**Comment by consuspk** [comment]
should we put those things in any html file and save it to anywhere on the same folder where .config is so you can change the template/text what ever you needed.

**Comment by Xi23000** [comment]
Yes, that works for now, good temporary solution.

**Comment by consuspk** [comment]
Added file "Resources/OrderEmailContent.html", you can edit content here but leave the strings that are in brackets "[...]"

**Comment by Xi23000** [comment]
Where is this located?

**Comment by Xi23000** [comment]
This is great, and to specify the recipients?

**Comment by consuspk** [comment]
one bcc field is added in web.config

**Comment by consuspk** [comment]
to email is customer email

**Comment by consuspk** [comment]
web.config is on root folder

**Comment by Xi23000** [comment]
OK, I'll test this
